name: translator_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  translator: ^0.1.7 # Add this line to include the translator package
  get: ^4.6.5
  http: ^0.13.6
  flutter_dropzone: ^4.2.1
  cupertino_icons: ^1.0.2 # Properly aligned
  dotted_border: ^2.1.0 # Correctly aligned this package
  speech_to_text: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
